### ISSUE TITLE
Undeclared variables

### ISSUE THREAD

**Issue by Mr-iX** [microsoft/AzureFunctionforSplunkVS#24]
@sebastus 
Now I got this error:
`Microsoft.Azure.WebJobs.Host: Error indexing method 'FaultProcessor'. Microsoft.Azure.WebJobs.Host: '%output-hub-name-proxy%' does not resolve to a value.`

After defining this parameter in the application settings, I get this error:
```
The following 6 functions are in error:
EhActivityLogsExt: Microsoft.Azure.WebJobs.Host: Error indexing method 'EhActivityLogsExt'. Microsoft.Azure.WebJobs.Host: Unable to resolve the value for property 'EventHubAttribute.Connection'. Make sure the setting exists and has a valid value.
EhDiagnosticLogsExt: Microsoft.Azure.WebJobs.Host: Error indexing method 'EhDiagnosticLogsExt'. Microsoft.Azure.WebJobs.Host: Unable to resolve the value for property 'EventHubAttribute.Connection'. Make sure the setting exists and has a valid value.
EhLadTelemetryExt: Microsoft.Azure.WebJobs.Host: Error indexing method 'EhLadTelemetryExt'. Microsoft.Azure.WebJobs.Host: Unable to resolve the value for property 'EventHubAttribute.Connection'. Make sure the setting exists and has a valid value.
EhMetricsExt: Microsoft.Azure.WebJobs.Host: Error indexing method 'EhMetricsExt'. Microsoft.Azure.WebJobs.Host: Unable to resolve the value for property 'EventHubAttribute.Connection'. Make sure the setting exists and has a valid value.
EhWadTelemetryExt: Microsoft.Azure.WebJobs.Host: Error indexing method 'EhWadTelemetryExt'. Microsoft.Azure.WebJobs.Host: Unable to resolve the value for property 'EventHubAttribute.Connection'. Make sure the setting exists and has a valid value.
FaultProcessor: Microsoft.Azure.WebJobs.Host: Error indexing method 'FaultProcessor'. Microsoft.Azure.WebJobs.Host: Unable to resolve the value for property 'EventHubAttribute.Connection'. Make sure the setting exists and has a valid value.
```

_Originally posted by @Mr-iX in https://github.com/microsoft/AzureFunctionforSplunkVS/issues/20#issuecomment-512819124_

**Comment by zchef2k** [comment]
I am encountering this, as well. Nothing seems to be retrieved from the event hub.

**Comment by zchef2k** [comment]
> @sebastus
> Now I got this error:
> `Microsoft.Azure.WebJobs.Host: Error indexing method 'FaultProcessor'. Microsoft.Azure.WebJobs.Host: '%output-hub-name-proxy%' does not resolve to a value.`
> 
> After defining this parameter in the application settings, I get this error:
> 
> ```
> The following 6 functions are in error:
> EhActivityLogsExt: Microsoft.Azure.WebJobs.Host: Error indexing method 'EhActivityLogsExt'. Microsoft.Azure.WebJobs.Host: Unable to resolve the value for property 'EventHubAttribute.Connection'. Make sure the setting exists and has a valid value.
> EhDiagnosticLogsExt: Microsoft.Azure.WebJobs.Host: Error indexing method 'EhDiagnosticLogsExt'. Microsoft.Azure.WebJobs.Host: Unable to resolve the value for property 'EventHubAttribute.Connection'. Make sure the setting exists and has a valid value.
> EhLadTelemetryExt: Microsoft.Azure.WebJobs.Host: Error indexing method 'EhLadTelemetryExt'. Microsoft.Azure.WebJobs.Host: Unable to resolve the value for property 'EventHubAttribute.Connection'. Make sure the setting exists and has a valid value.
> EhMetricsExt: Microsoft.Azure.WebJobs.Host: Error indexing method 'EhMetricsExt'. Microsoft.Azure.WebJobs.Host: Unable to resolve the value for property 'EventHubAttribute.Connection'. Make sure the setting exists and has a valid value.
> EhWadTelemetryExt: Microsoft.Azure.WebJobs.Host: Error indexing method 'EhWadTelemetryExt'. Microsoft.Azure.WebJobs.Host: Unable to resolve the value for property 'EventHubAttribute.Connection'. Make sure the setting exists and has a valid value.
> FaultProcessor: Microsoft.Azure.WebJobs.Host: Error indexing method 'FaultProcessor'. Microsoft.Azure.WebJobs.Host: Unable to resolve the value for property 'EventHubAttribute.Connection'. Make sure the setting exists and has a valid value.
> ```
> 
> _Originally posted by @Mr-iX in [#20 (comment)](https://github.com/microsoft/AzureFunctionforSplunkVS/issues/20#issuecomment-512819124)_

sebastus,

I'm not sure which of these was the trick, but create a new setting called "outputHubConnection" with a value set to the Event Hub namepsace's connection string. I also created a second hub and used its name as the value for the previosuly defined 'output-hub-name-proxy', although I don't see that any messages are landing on that hub. Regardless, I have HEC events in splunk now.

**Comment by sebastus** [comment]
That's a setting. Add to function settings.

**Comment by sebastus** [comment]
set it to "collector-to-proxy". It's a recent addition so I haven't fixed
the ARM template yet.

**Comment by sebastus** [comment]
A more complete answer:

If you're monitoring more than one subscription with a single Splunk instance, you're faced with a difficult choice: either expose HEC to the internet or add some network peering / vpn configuration to your architecture. This is because a function in one subscription can't see a HEC in a private network in a different subscription. Functions connect out by default on the internet. 

To resolve this problem, I added a new output binding: event hub, and a new function proxy. The function proxy is installed in the same subscription/vnet as the Splunk box. Functions in other subscriptions output to a single event hub, which is consumed by that proxy function. The proxy function connects out to the event hub (and is triggered by it), so there is no inbound connection.

This necessitated the addition of said output event hub *always*, not just if you're going to use it. It's a quirk of how functions connects out to a hub. The two settings required by it are:

output-hub-name-proxy: set this to 'collector-to-proxy'
outputHubConnection: set this to a valid hub connection string.

Here's the proxy function repo: https://github.com/sebastus/functionProxyDotnet complete with a readme and an architecture diagram.
